### ISSUE TITLE
3.9 support?

### ISSUE THREAD

**Issue by jamespo** [bamthomas/aioimaplib#64]
Currently running the example with python 3.9.4 errors are thrown (presumably due to changes in asyncio):

```
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<IMAP4ClientProtocol.welcome() done, defined at /home/james/dls/aioimaplib/aioimaplib/aioimaplib.py:298> exception=TypeError("object Condition can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/james/dls/aioimaplib/aioimaplib/aioimaplib.py", line 300, in wrapper
    with await self.state_condition:
TypeError: object Condition can't be used in 'await' expression
Traceback (most recent call last):
```

I intend to look into this, although my experience with async is limited.

**Comment by bamthomas** [comment]
hmm probably linked to this : 
https://github.com/bamthomas/aioimaplib/pull/59#issuecomment-817753222

I have pushed a fix https://github.com/bamthomas/aioimaplib/commit/76bd59f0a1750847257ef0734b9b8960fc276978 could you test with it (executing tests on the master) ?

**Comment by jamespo** [comment]
I get complaint about "with await" elsewhere (line 300) with that fix, I will test more this evening / over the weekend.

```
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<IMAP4ClientProtocol.welcome() done, defined at /home/james/.venvs/39/lib/python3.9/site-packages/aioimaplib-0.8.0-py3.9.egg/aioimaplib/aioimaplib.py:298> exception=TypeError("object Condition can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/james/.venvs/39/lib/python3.9/site-packages/aioimaplib-0.8.0-py3.9.egg/aioimaplib/aioimaplib.py", line 300, in wrapper
    with await self.state_condition:
TypeError: object Condition can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/james/.venvs/39/lib/python3.9/site-packages/aioimaplib-0.8.0-py3.9.egg/aioimaplib/aioimaplib.py", line 595, in wait
    await self.state_condition.wait_for(lambda: state_re.match(self.state))
  File "/usr/lib/python3.9/asyncio/locks.py", line 317, in wait_for
    await self.wait()
  File "/usr/lib/python3.9/asyncio/locks.py", line 290, in wait
    await fut
asyncio.exceptions.CancelledError
```

**Comment by bamthomas** [comment]
it should work now I will probably release a 0.9 soon with the byte/string PR
