### ISSUE TITLE
Fix compatibility with Python 3.10+

### ISSUE THREAD

**Issue by ThiefMaster** [bamthomas/aioimaplib#82]
It would be nice if it worked on modern Python versions as well :)

```
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<BaseEventLoop.create_connection() done, defined at /home/adrian/.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py:972> exception=ConnectionResetError() created at /home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/aioimaplib/aioimaplib.py:688>
source_traceback: Object created at (most recent call last):
  File "/home/adrian/dev/imapwatch/./imapwatch.py", line 131, in <module>
    main()
  File "/home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/adrian/dev/imapwatch/./imapwatch.py", line 127, in main
    asyncio.run(async_main(mailbox, host, user, password, test_mode, include_seen), debug=True)
  File "/home/adrian/.pyenv/versions/3.10.5/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/adrian/.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/home/adrian/.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/home/adrian/.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py", line 1888, in _run_once
    handle._run()
  File "/home/adrian/.pyenv/versions/3.10.5/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/adrian/dev/imapwatch/./imapwatch.py", line 111, in async_main
    await idle_loop(mailbox, host, user, password, test_mode, include_seen)
  File "/home/adrian/dev/imapwatch/./imapwatch.py", line 75, in idle_loop
    imap_client = IMAP4_SSL(host=host, timeout=30)
  File "/home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/aioimaplib/aioimaplib.py", line 829, in __init__
    super().__init__(host, port, loop, timeout, None, ssl_context)
  File "/home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/aioimaplib/aioimaplib.py", line 682, in __init__
    self.create_client(host, port, loop, conn_lost_cb, ssl_context)
  File "/home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/aioimaplib/aioimaplib.py", line 835, in create_client
    super().create_client(host, port, loop, conn_lost_cb, ssl_context)
  File "/home/adrian/dev/imapwatch/.venv/lib/python3.10/site-packages/aioimaplib/aioimaplib.py", line 688, in create_client
    local_loop.create_task(local_loop.create_connection(lambda: self.protocol, host, port, ssl=ssl_context))
Traceback (most recent call last):
  File "/home/adrian/.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/home/adrian/.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
ConnectionResetError
```

**Comment by ThiefMaster** [comment]
OK this is even weirder: On Python 3.9.15 installed via pyenv it works fine, but on 3.9.15 installed via Gentoo's portage package manager (both using a virtualenv created with `python -m venv`) I get the same error...

**Comment by ThiefMaster** [comment]
I think this was because of a terribly outdated TLS config on the server.
